name: Release

on:
  push:
    tags:
      - '*'

env:
  IMAGE: ghcr.io/luncher-org/hyperkube

jobs:
  build-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # needed for the Vault authentication
    strategy:
      fail-fast: true
      matrix:
        os: [linux]
        arch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Environment Variables
        run: |
          echo "ARCH=${{ matrix.arch }}" >> "$GITHUB_ENV"
          echo "K8S_VERSION=$( echo ${{ github.ref_name }} | tr -s " " | cut -d "-" -f1 )" >> "$GITHUB_ENV"
          echo "TAG=$IMAGE:$( echo ${{ github.ref_name }} )" >> "$GITHUB_ENV"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Prepare binaries
        run: make k8s-binaries
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platforms }}
          push: true
          outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=Luncher Hyperkube image
          tags: ${{ env.TAG }}
